on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    permissions:
      contents: write, read
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - run: npm install
      - run: npm install -g jest
      - run: jest test
      - run: jest --coverage
    
      - uses: actions/checkout@v3
      - run: |
          LINES=$(jq '.total.lines.pct' coverage/coverage-summary.json)
          STATEMENTS=$(jq '.total.statements.pct' coverage/coverage-summary.json)
          FUNCTIONS=$(jq '.total.functions.pct' coverage/coverage-summary.json)
          BRANCHES=$(jq '.total.branches.pct' coverage/coverage-summary.json)

          echo "coverage: $LINES% lines, $STATEMENTS% statements, $FUNCTIONS% functions, $BRANCHES% branches" >> $GITHUB_ENV
      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ## Jest Coverage Report
            ${{ env.coverage }}
          edit-mode: replace