on:
  push:
    branches:

  pull_request:
    types: [opened, reopened]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - run: npm install
      - run: npm install -g jest
      - run: jest test
      - run: jest --coverage
    
  comment:
    permissions:
      contents: write
      pull-requests: write
      steps: 
        - uses: peter-evans/create-or-update-comment@v4
          run: |
              LINES=$(jq '.total.lines.pct' coverage/coverage-summary.json)
              STATEMENTS=$(jq '.total.statements.pct' coverage/coverage-summary.json)
              FUNCTIONS=$(jq '.total.functions.pct' coverage/coverage-summary.json)
              BRANCHES=$(jq '.total.branches.pct' coverage/coverage-summary.json)

              echo "::set-env name=coverage::Lines: $LINES, Statements: $STATEMENTS, Functions: $FUNCTIONS, Branches: $BRANCHES"
              
          with:
            comment-id: ${{ github.event.comment.id }}
            issue-number: ${{ github.event.pull_request.number }}
            body: |
              ## Jest Coverage Report
              ${{ env.coverage }}
            edit-mode: replace