on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - run: npm install
      - run: npm install -g jest
      - run: jest test
      - run: jest --coverage
    
  comment:
    permissions:
      contents: write
      pull-requests: write
      steps: 
      - uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ## Test results
            ${{ steps.jest.outputs.result }}